### Create Order
POST http://localhost:3000/orders/create
Content-Type: application/json

{
  "product": "Product 1",
  "quantity": 2,
  "total": 2000
}

### Set Order as Completed
PATCH http://localhost:3000/orders/complete/3

### Get all orders for a user
GET http://localhost:3000/orders/my-orders